### ISSUE TITLE
Consider moving places.js data into meetup repository

### ISSUE THREAD

**Issue by jepp2078** [cloud-native-nordics/artwork#12]
@kaspernissen and i had a discussion about moving the data from places.js into the meetup repository.

This would allow us to expose the data from the stats-api.

This repository would then need to pull in the places data from the stats-api to generate the maps.

**Comment by luxas** [comment]
Will be fixed with: https://github.com/cloud-native-nordics/meetups/pull/92

**Comment by luxas** [comment]
Actually, when thinking about it, it'd be better to consume this information from the stats-api, rather than downloading the `config.json` blob. Reopening until we have stats-api support for lat/lng.
cc @kaspernissen
