### ISSUE TITLE
Relicensing the artwork to CC license

### ISSUE THREAD

**Issue by idvoretskyi** [cloud-native-nordics/artwork#2]
The artwork here is licensed under Apache 2 license, which was not designed to be used with a similar type of content.

Instead, you may consider relicensing the artwork to one of the Creative Commons licenses (https://creativecommons.org/licenses/), for example CC (https://creativecommons.org/licenses/by/4.0/), which was the inspiration for the Linux Foundation Trademark policy - https://www.linuxfoundation.org/trademark-usage/.

**Comment by idvoretskyi** [comment]
cc @kaspernissen @luxas

**Comment by kaspernissen** [comment]
That makes sense. We should probably copy something like this: https://github.com/exercism/docs/blob/master/LICENSE

What do you think, @luxas?
