### ISSUE TITLE
Permission issue with generator

### ISSUE THREAD

**Issue by kaspernissen** [cloud-native-nordics/artwork#7]
I'm trying to generate the missing backgrounds, but running e.g.
`make LOCATION=aarhus` fails with the following permission error:

```
...
docker run -it --rm \
		-v /Users/kaspernissen/Development/cloud-native-nordics/artwork/slide-background/generator:/generator \
		-w /generator \
		-u 501:20 \
		--net container:tmp_bg_webserver \
		puppeteer \
		/bin/sh -c "\
		npm install && \
		./capture.js"
npm WARN background-generator@1.0.0 No repository field.

npm ERR! path /.npm
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall mkdir
npm ERR! Error: EACCES: permission denied, mkdir '/.npm'
npm ERR!  [Error: EACCES: permission denied, mkdir '/.npm'] {
npm ERR!   stack: "Error: EACCES: permission denied, mkdir '/.npm'",
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/.npm'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).
make: *** [all] Error 243
```
/cc @luxas

**Comment by vstirbu** [comment]
Seems like you are root in the container. Does it work if you add `--unsafe-perm` to the `npm install && \` line?

**Comment by luxas** [comment]
Hmm, are you running on a Mac? :)
I'm not sure why npm tries to make the `/.npm` directory actually...

You could workaround this (most probably) by
a) removing `-u 501:20`
b) adding `--unsafe-perm` to `npm install` as @vstirbu said
c) appending `chown -R 501:20 .` to the command list (to fix the permissions after the generation)

**Comment by kaspernissen** [comment]
Yes, running on a Mac :) 

The `--unsafe-perm` didn't help, tried to remove the user as well. No luck either. Now it runs without error but the map is not used as a background. I put my API key in the `.gmap_api_key` and also enabled the Maps API in the console. Any ideas?

**Comment by luxas** [comment]
Still an issue?

**Comment by kaspernissen** [comment]
Haven't tried since last time. But didn't manage to get it working with any of the workarounds.

**Comment by Solisol** [comment]
![screenshot](https://user-images.githubusercontent.com/3530296/64243671-06115d00-cf08-11e9-8a79-2b69f3daa0e4.png)
It seems to me that it doesn't manage to finish drawing the map..? Sometimes I get no map whatsoever, this time I got this.

**Comment by kaspernissen** [comment]
Same here:
![screenshot](https://user-images.githubusercontent.com/4429108/64247397-137e1580-cf0f-11e9-929d-a09e97e12f98.png)
Both @Solisol and I are using a mac, it may seem that this issue is isolated to MacBook, but not completely sure.

**Comment by luxas** [comment]
Hmm strange @vstirbu any ideas? Just add a timeout 😂?
The above issue is different from the first one, so it might be solved then?

**Comment by kaspernissen** [comment]
Yes, I think the initial issue was solved by executing with `sudo`.

**Comment by vstirbu** [comment]
The partial rendering is not caused by Mac. The container that generates the image is [linux](https://github.com/cloud-native-nordics/artwork/blob/5383c4786ec8028f074c0ce38eb30c43ae5ae66e/slide-background/generator/Makefile#L19).

ps: and if the original issue is solved a new issue should be opened... 🖖

**Comment by kaspernissen** [comment]
Increasing the timeout solved the second issue. I will add a note to the readme, to run `sudo make LOCATION=<city>`
